// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjtCHU3L1YCvJMLaOXoJNZMDKxT0pPo-s',
    appId: '1:499157306831:web:233f835318d46b8f92d6ba',
    messagingSenderId: '499157306831',
    projectId: 'flutterapptp6-3b134',
    authDomain: 'flutterapptp6-3b134.firebaseapp.com',
    storageBucket: 'flutterapptp6-3b134.firebasestorage.app',
    measurementId: 'G-J3VZ3WRR37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyJ5tPuoEQkx8QaTMY5MaQgevKpsiMx3Y',
    appId: '1:499157306831:android:2406f0517fd1824892d6ba',
    messagingSenderId: '499157306831',
    projectId: 'flutterapptp6-3b134',
    storageBucket: 'flutterapptp6-3b134.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ITgoMEMbrtDuJm4hT1sPIfK0qihTm60',
    appId: '1:499157306831:ios:443d3332ad00f0b192d6ba',
    messagingSenderId: '499157306831',
    projectId: 'flutterapptp6-3b134',
    storageBucket: 'flutterapptp6-3b134.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ITgoMEMbrtDuJm4hT1sPIfK0qihTm60',
    appId: '1:499157306831:ios:443d3332ad00f0b192d6ba',
    messagingSenderId: '499157306831',
    projectId: 'flutterapptp6-3b134',
    storageBucket: 'flutterapptp6-3b134.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjtCHU3L1YCvJMLaOXoJNZMDKxT0pPo-s',
    appId: '1:499157306831:web:233f835318d46b8f92d6ba',
    messagingSenderId: '499157306831',
    projectId: 'flutterapptp6-3b134',
    authDomain: 'flutterapptp6-3b134.firebaseapp.com',
    storageBucket: 'flutterapptp6-3b134.firebasestorage.app',
    measurementId: 'G-J3VZ3WRR37',
  );
}
